castai/helm-charts

charts/castai-evictor/Chart.yaml

New version of Evictor targets only Linux/amd64 nodes.

[castai-evictor] Bump version.

---

.github/workflows/lint-test.yaml
charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/deployment.yaml
kind.yaml

Currently the cluster-controller pods can get scheduled on the same node which can cause FAILED mode if the node goes offline and the pods can't land somewhere else. In order to reduce the fragility of cluster-controller I have added a podAntiAffinity rule to force them onto separate nodes.

[castai-cluster-controller] NOJIRA: add podantiaffinity to cluster-controller template

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/deployment.yaml

Set automountServiceAccountToken=true for autoscaler POD. Default is expected to be true, but there were cases on some clusters that service account token was not mounted.

[castai-agent] Add automountServiceAccountToken=true.

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/deployment.yaml
charts/castai-cluster-controller/templates/secret.yaml
charts/castai-cluster-controller/values.yaml

Allow users to provide API key in their own secret via a reference.

[castai-cluster-controller] add apiKeySecretRef option

---

charts/castai-agent/Chart.yaml

pipelines didn't catch concurrent update to 33.2 version

[castai-agent] version collision due to concurrent PRs

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-deployment.yaml
charts/castai-agent/values.yaml

The only change between v0.8.3 vs 0.8.4 is a multi-arch build https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/releases/tag/v0.8.4

[castai-agent] update image for clusterVPA - arm64 support

---

charts/castai-agent/Chart.yaml
charts/castai-agent/values.yaml

Prefer CAST AI nodes during agent scheduling to be able to call CSP metadata API by inheriting node instance profiles.

[castai-agent] prefer castai nodes during scheduling

---

charts/castai-pod-node-lifecycle/Chart.yaml

[Releases](https://github.com/castai/k8s-webhooks/releases)

[castai-pod-node-lifecycle] Bump version from v0.17.0 to v0.18.0

---

charts/castai-pod-node-lifecycle/Chart.yaml

[Releases](https://github.com/castai/k8s-webhooks/releases)

[castai-pod-node-lifecycle] Bump version to v0.19.0

---

charts/castai-pod-node-lifecycle/Chart.yaml

Spot-webhook
* should look at Pod status for partial distribution
* CSU-453 fix annotation override bug when global DefaultToSpot is True

[castai-pod-node-lifecycle] terminating pods and annotation fix

---

charts/castai-cluster-controller/Chart.yaml

- `Log real reason of shutdown of the controller.`  https://github.com/castai/cluster-controller/releases/tag/v0.37.5

[castai-cluster-controller] Update helm chart 

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/rbac.yaml

Breaking change: Remove cluster-controller RBAC write permissions.
In order for cluster-controller to support chartUpsert actions, cluster have to be running cluster-controller v0.38.0 version.

[castai-cluster-controller] feat: Remove cluster-controller RBAC write permissions

---

.github/workflows/release.yaml

Egressd is released in it's owed repo. Only chart content is synced.

Add skip_existing to chart release

---

charts/castai-agent/Chart.yaml
charts/castai-agent/README.md
charts/castai-agent/templates/rbac.yaml
charts/castai-agent/values.yaml

This PR removes access to `configmaps` from `ClusterRole` and replaces it with configurable namespace-level RBAC.

[castai-agent] remove cluster level configmap access

---

charts/castai-hibernate/Chart.yaml
charts/castai-hibernate/README.md
charts/castai-hibernate/templates/pause-cronjob.yaml
charts/castai-hibernate/templates/resume-cronjob.yaml
charts/castai-hibernate/templates/secret.yaml
charts/castai-hibernate/values.yaml

Adding the ability to use an existing secret for the APIKey rather than creating a new one and requiring the API_KEY to be passed into the helm chart.
This fixed #419 .
This is just to help - its not a big change and not worried if you would rather implement it your own way.

[castai-hibernate] - Adding in the option to reference an existing secret for the API Key

---

kube-linter-config.yaml

The chart contains Nvidia's DCGM expoter which
can not run in unpriviledged mode
We configured the linter in the gpu-metrics-exporter repo 
to check for the other issues, so the chart will not be 
completely unlinted

Exclude gpu-metrics-exporter chart from linting

---

charts/castai-hibernate/Chart.yaml
charts/castai-hibernate/templates/pause-cronjob.yaml
charts/castai-hibernate/templates/resume-cronjob.yaml

Adjusting the timezone k8s versions to the hibernate cronjobs from 1.27 to 1.25.
Ref: https://github.com/castai/hibernate/pull/21/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R45

[castai-hibernate] update k8s support for timezone

---

charts/castai-pod-node-lifecycle/Chart.yaml

See https://github.com/castai/k8s-webhooks/pull/47 for what changed

[castai-pod-node-lifecycle]  CSU-1569: Disable TLS 1.2 and below in spot-lifecycle webhook

---

charts/castai-agent/Chart.yaml

Relevant Agent release here: castai/k8s-agent#174

[castai-agent] chore: bump agent version: send deltas with a non-sliding interval

---

charts/castai-spot-handler/Chart.yaml

Release for spot-handler app - https://github.com/castai/spot-handler/releases/tag/v0.12.0

[castai-spot-handler] Chore: Bump spot-handler to go 1.22 version

---

charts/castai-cluster-controller/Chart.yaml

Release for app - https://github.com/castai/cluster-controller/releases/tag/v0.43.0

[castai-cluster-controller] Chore: Bump cluster controller to go 1.22 version

---

charts/castai-cluster-controller/Chart.yaml

Bumps chart to use this release https://github.com/castai/cluster-controller/releases/tag/v0.44.0

[castai-cluster-controller] KUBE-479: Bump app and chart version for cluster-controller

---

charts/castai-hibernate/Chart.yaml

Update Helm Chart for v0.11
This update bumps the Helm chart version to reflect the release of v0.11 of the application.
Key Changes in app :
•	Removed Fallback Label: The fallback label has been removed from the application. As a result, the hibernation node will now appear as a Spot node but will function as a demand node with a pause label.
•	Reason for Change: The autoscaler was frequently replacing the fallback node, causing instability. This update addresses that issue by removing the fallback label.

[castai-hibernate] hibernate app bump 

---

charts/castai-hibernate/Chart.yaml
charts/castai-hibernate/README.md
charts/castai-hibernate/templates/pause-cronjob.yaml
charts/castai-hibernate/templates/resume-cronjob.yaml
charts/castai-hibernate/values.yaml

Related to https://github.com/castai/hibernate/issues/38

[castai-hibernate] #506 Added API_URL variable

---

charts/castai-cluster-controller/Chart.yaml

Seeing nodes where kube-proxy fails to start, seems to happen mostly on v0.52+ (although hard to reproduce consistently). Temporary downgrade until we resolve issue.

[castai-cluster-controller] Downgrade CC version due to CSR instabilities

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/rbac.yaml

Example new kube-system Role with labels:
```
kubectl get Role -n kube-system castai-agent -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
annotations:
meta.helm.sh/release-name: mycastai-agent
meta.helm.sh/release-namespace: castai-agent2
creationTimestamp: "2024-10-14T10:39:18Z"
labels:
app.kubernetes.io/instance: mycastai-agent
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: castai-agent
app.kubernetes.io/version: v0.64.0
helm.sh/chart: castai-agent-0.79.0
name: castai-agent
namespace: kube-system
resourceVersion: "91193"
uid: 7452e15c-1110-4f66-a810-28b43d1cd8a3
rules:
- apiGroups:
- ""
resources:
- configmaps
verbs:
- get
- list
- watch
```

[castai-agent] Add standard labels and annotations for kube-system Role

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/ci/test-values.yaml
charts/castai-db-optimizer/templates/deployment.yaml
charts/castai-db-optimizer/templates/envoy_config.yaml
charts/castai-db-optimizer/values.yaml

Example output:
```
Events:
Type     Reason     Age              From               Message
----     ------     ----             ----               -------
Normal   Scheduled  9s               default-scheduler  Successfully assigned default/castai-db-optimizer-589fd9dfcf-8rtmg to tilt-control-plane
Normal   Pulled     9s               kubelet            Container image "us-docker.pkg.dev/castai-hub/library/query-processor:v0.1.0-rc.19" already present on machine
Normal   Created    9s               kubelet            Created container query-processor
Normal   Started    9s               kubelet            Started container query-processor
Normal   Pulled     9s               kubelet            Container image "us-docker.pkg.dev/castai-hub/library/dbo-proxy:4.48.1" already present on …
```

[castai-db-optimizer] add proxy readiness probe

---

charts/castai-pod-pinner/Chart.yaml
charts/castai-pod-pinner/README.md

Regular version upgrade to [pod pinner v1.0.3](https://github.com/castai/pod-pinner/releases/tag/v1.0.3).

[castai-pod-pinner] Use image v1.0.3

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/templates/clusterrole.yaml
charts/castai-evictor/templates/deployment.yaml
charts/castai-evictor/values.yaml

This commit exposes settings that control LIVE migration in the Evictor Helm chart.
The settings let the user instruct Evictor to try or not try using LIVE migrations when evicting nodes.

[castai-evictor] feat(evictor): expose LIVE migration settings

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/README.md
charts/castai-cluster-controller/templates/config.yaml
charts/castai-cluster-controller/templates/deployment.yaml
charts/castai-cluster-controller/values.yaml

Following the best practices of GitOps should allow minimum/no manual intervention required from the developers. When using crossplane to deploy the castai cluster resources, a secret containing the value of clusterID is stored in the cluster. These changes allow reading the value of the field "clusterID" from the secret instead of someone having to manually add it in the values files.

[castai-cluster-controller] add support for clusterIDSecretRef

---

charts/castai-spot-handler/Chart.yaml
charts/castai-spot-handler/README.md
charts/castai-spot-handler/templates/daemonset.yaml
charts/castai-spot-handler/values.yaml

Following the best practices of GitOps should allow minimum/no manual intervention required from the developers. When using crossplane to deploy the castai cluster resources, a secret containing the value of clusterID is stored in the cluster. These changes allow reading the value of the field "clusterID" from the secret instead of someone having to manually add it in the values files.

[castai-spot-handler] add support for clusterIDSecretRef

---

charts/castai-audit-logs-receiver/Chart.yaml
charts/castai-audit-logs-receiver/templates/statefulset.yaml

affinity, nodeSelector, and tolerations are part of the pod spec, not the container.

[castai-audit-logs-receiver] Fix tolerations location

---

charts/castai-pod-mutator/Chart.yaml
charts/castai-pod-mutator/README.md

Bump the chart version to 0.0.9 and the app version to v0.0.5 in both the Chart.yaml file and the README.md badge. This ensures consistency and reflects the latest updates.

[castai-pod-mutator] Update chart and app versions to 0.0.9 and v0.0.5

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/rbac.yaml

I don't think that leases need to be scoped at the clusterrole level and instead it can be scoped at the role them in the castai-agent ns

[castai-agent] moving leader election to role instead of clusterrole

---

.github/workflows/lint-test.yaml
.github/workflows/validate-pr.yaml
charts/castai-agent/Chart.yaml
cnab-config/castai-agent/mainTemplate.json
scripts/verify-cnab-package.sh

Azure Resource Manager (ARM) templates were using a deprecated API version. 
Hence, the Cloud Native Application Bundle (CNAB) could not be built and released to Azure marketplace.

[castai-agent] fix: Azure CNAB pipeline

---

.github/workflows/release-cnab.yaml
.github/workflows/release.yaml

We want to publish a modified helm chart for Temporal
but it requires a few repos to be added to helm so the Release
step can succeed.
We need to manually add repos for deps due to bug in https://github.com/helm/chart-releaser/issues/135

Add repos that are required by the Temporal helm chart

---

charts/castai-cluster-controller/Chart.yaml

Corresponds to app release [v0.54.9](https://github.com/castai/cluster-controller/releases/tag/v0.54.9).

[castai-cluster-controller] v0.78.5 (app v0.54.9)

---

charts/castai-workload-autoscaler/README.md

**Description**
- Describe how users can fetch the Helm chart manifest for later review e.g. by the security team.
- I tested it on my fork repo and the release proces won't be impacted by this folder, see: https://github.com/mszostok/castai-helm-charts
- Also WA releases should not be a problem: https://github.com/mszostok/castai-helm-charts/pull/4
Possible follow-up steps:
1. Mirror the Helm chart here anyway
2. Or run the `helm-docs` in the source repo and commit it here.

[workload-autoscaler] Add README.md describing how to fetch manifests

---

charts/castai-audit-logs-receiver/Chart.yaml

* New version includes updated go-resty library

[castai-audit-logs-receiver] bump to latest version

---

charts/castai-agent/Chart.yaml
charts/castai-agent/README.md
charts/castai-agent/values.yaml

This PR will avoid the confusion of using GKS instead of GKE as the provider for castai-agent values.

[castai-agent] avoid confusion on gke as cloud provider in values

---

charts/castai-audit-logs-receiver/Chart.yaml
charts/castai-audit-logs-receiver/README.md
charts/castai-audit-logs-receiver/templates/statefulset.yaml
charts/castai-audit-logs-receiver/values.yaml

Currently the clusterid filter is included in the config block as an inline string, which is loaded into the configmap. This PR will now allow this to be set outside of the config block, allowing the users to have an option to either use
`castai.clusterID` or `castai.clusterIdSecretKeyRef` 
similar to the other components like cluster-controller, evictor.

[castai-audit-logs-receiver] add an option for clusterIdSecretKeyRef

---

charts/castai-pod-mutator/Chart.yaml
charts/castai-pod-mutator/README.md
charts/castai-pod-mutator/templates/deployment.yaml
charts/castai-pod-mutator/values.yaml

Env vars could be set by providing them in values.yaml or using args 
> --set additionalEnv.test=1 --set additionalEnv.test2=2

[castai-pod-mutator] add additional env vars support to pod-mutator

---

charts/castai-cluster-controller/Chart.yaml

See https://github.com/castai/cluster-controller/releases/tag/v0.56.4

[castai-cluster-controller] Bump CC version with one that has metrics. 

---

charts/castai-cluster-controller/Chart.yaml

https://github.com/castai/cluster-controller/releases/tag/v0.57.0

[castai-cluster-controller] KUBE-996: bump controller

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/rbac.yaml
charts/castai-cluster-controller/values.yaml

The goal is to be able to not grant the cluster-controller write access on nodes when only the workload autoscaler is enabled and the node autoscaler is disabled.

[castai-cluster-controller] feat(cluster-controller): node rbac

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/deployment.yaml

Bumps CC to this release that fixes concurrency bug in logexporter - https://github.com/castai/cluster-controller/releases/tag/v0.57.2 
Also adds the metrics port to the deployment spec (not required but makes it easier to discover).

[castai-cluster-controller] Add metrics port to spec and bump CC

---

charts/castai-hibernate/Chart.yaml
charts/castai-hibernate/README.md
charts/castai-hibernate/templates/pause-cronjob.yaml
charts/castai-hibernate/values.yaml

**Changes**
- Added `hibernateNodeLabels` parameter to set Kubernetes labels on hibernate nodes
- Updated Chart version to `0.2.10` and appVersion to `v0.13`
- Added new `HIBERNATE_NODE_LABELS` environment variable to pause-cronjob
**Purpose**
- Enables better integration with CAST AI components and kube-system workloads that use nodeSelectors by allowing custom labels on hibernate nodes.
**Testing**
Verify hibernate functionality works with the new label support and labels are correctly applied to nodes.

[castai-hibernate] Hibernate Node Labels Support

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/rbac.yaml

Customers using `helm template` to deploy helm charts have rbac resources for the cluster controller output with metadata.namespace: default since in the template `metadata.namespace: {{ .Release.Namespace }}` is not present. This is due to a nuance with helm template vs install/upgrade.

[castai-cluster-controller] Apply {{ .Release.Namespace }} consistently in cluster-controller resources

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/templates/deployment.yaml
charts/castai-evictor/values.yaml

Prior to this commit, Evictor used the default Kubernetes client rate limiting settings. These settings were insufficient to operate in large enough clusters.
This commit exposes the environment variables that the updated Evictor binary can use to control its rate limiting settings.

[castai-evictor] feat: add Kubernetes client rate limiting controls

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/values.yaml

This commit bumps Evictor client rate limiter values to match those in Cluster Controller.

[castai-evictor] chore: bump rate limiter values

---

charts/castai-agent/Chart.yaml

We ran this agent version for over 24 hours. It contains some changes in the code that's collecting and uploading deltas (in order to retry on error).

[castai-agent] Chart v0.102.0 (app image v0.89.0)

---

charts/castai-ai-optimizer-proxy/Chart.yaml
charts/castai-ai-optimizer-proxy/README.md
charts/castai-ai-optimizer-proxy/values.yaml

Cast AI requires the deployment to be named `castai-ai-optimizer-proxy` to property identify its installation.

[castai-ai-optimizer-proxy] Set fullnameOverride for castai-ai-optimizer-proxy

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/README.md
charts/castai-cluster-controller/templates/deployment.yaml
charts/castai-cluster-controller/values.yaml

This PR adds support for injecting dynamic volumes and volumeMounts into the Helm chart templates. This enhancement enables users to provide arbitrary additional volumes and volume mounts via values.yaml, making the charts more flexible and extensible.
Motivation
Certain integrations (e.g. [Vault CSI Driver](https://developer.hashicorp.com/vault/docs/deploy/kubernetes/csi/examples)) require the injection of specific volumes and mounts at runtime, such as:
```
CSI-mounted secrets
Custom configuration volumes
Sidecar data sharing
```
Previously, these could only be added by modifying the chart templates directly or forking them. With this change, they can be specified dynamically at deploy time.

[castai-cluster-controller] Add support for dynamic volume

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/ci/test-values.yaml
charts/castai-db-optimizer/templates/service.yaml

- Fix `targetPort` field to use `$endpoint.targetPort` instead of `$endpoint.port` for consistency
- Update unnamed endpoint port mapping to use `servicePort` and `targetPort` fields explicitly
- Standardize port assignment logic between named and unnamed endpoint services
- Remove inconsistent port field usage across service templates
This change resolves a critical service configuration bug where customers specified database ports but the backend secretly transformed them, causing connection failures when customers attempted to connect using their original specified ports.
The standardization of port assignment logic eliminates operational complexity between named and unnamed endpoints, making the configuration more predictable and reducing the potential for similar port mapping bugs in …

[castai-db-optimizer] POLY-745: Fix service port mapping and standardize endpoint config

---

charts/castai-watchdog/Chart.yaml
charts/castai-watchdog/README.md
charts/castai-watchdog/templates/config.yaml
charts/castai-watchdog/templates/deployment.yaml
charts/castai-watchdog/templates/service-account.yaml
charts/castai-watchdog/values.yaml

- add support for notifications via HTTP webhooks
- refactor the config management a bit, use a config file instead of environment variables, where it was possible

[castai-watchdog] refactor chart and add support for HTTP notification webhooks

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/ci/test-values.yaml
charts/castai-db-optimizer/templates/service.yaml

servicePort and targetPort values being saved as `0` for deployments. Reverted kubecast changes, need to revert the matching changes here, too.

[castai-db-optimizer] NOJIRA: Revert Merge Commit 7bc1252

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/templates/envoy_config.yaml
charts/castai-db-optimizer/templates/service.yaml

- Fix service  references to use correct endpoint value
- Add comments clarifying port mapping flow in service templates
- Update Envoy config comments for upstream database endpoints
- Bump chart version to 0.43.1
This fixes a critical issue where services were referencing the wrong port field, causing connection failures between services and the database optimizer proxy pods.

[castai-db-optimizer] fix broken service ports in service chart

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/values.yaml

[castai-evictor] Enable live migrations by default.

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/templates/_versions.tpl
charts/castai-db-optimizer/templates/deployment.yaml
charts/castai-db-optimizer/values.yaml

Adding required env variables for core dump collection to work properly:
`API_URL` -- same as for query-processor
`CACHE_GROUP_ID` -- same as for query-processor
`COREDUMP_COLLECTION` -- by default "None" which disables the collection. To enable switch to "Full".
Changing the entrypoint for proxy container -- now it's a shell wrapper that monitors envoy binary and collects coredumps if needed.

[castai-db-optimizer] core dump collection for dbo proxy

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/ci/test-values.yaml
charts/castai-db-optimizer/templates/deployment.yaml

In order to collect core dumps, `proxy` container (part of DBO) needs to run as root and has the write access to root.
This happens only if `proxy.coredumpCollectionMode` is set to `"Full"`, otherwise the restrictive security context is used.

[castai-db-optimizer] elevated security context for dbo diagnostics

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/templates/dbo-collector.yaml

Addresses deployment errors such as:
```
error when patching "/dev/shm/1297378085": Deployment.apps "db-optimizer-**************************************-index-advisor-collector" is invalid: [spec.selector.matchLabels: Invalid value: "db-optimizer-**************************************-index-advisor-collector": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:
```

[castai-db-optimizer] Truncate `dbo-collector` name label to 63 chars

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/resource-quota.yaml
charts/castai-cluster-controller/templates/secret.yaml

- When running provisioning with terragrunt using this example [eks-clusters](https://github.com/castai/terraform-provider-castai/tree/master/examples/eks/eks_clusters) , we have identified the terragrunt is not retrieving properly the namespace. 
- Making the adjustment on tf like below, secret resource got created properly. 
```
castai_cluster_controller_values = [
<<-YAML
createNamespace: true
YAML
]
```
- Based on that, I have added like others template resources the call for namespace like the best practices stand for.

[castai-cluster-controller] bugfix secret ns cluster-controller
