castai/helm-charts

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/rbac-agent.yaml
charts/castai-cluster-controller/values.yaml

Adding required permissions for creating events to support new create event cluster action.

[castai-cluster-controller] feat: cluster-controller v0.4.0

---

charts/castai-pod-node-lifecycle/Chart.yaml
charts/castai-pod-node-lifecycle/templates/pod-disrubtion-budget.yaml

Fix castai-pod-node-lifecycle pod-disrubtion-budget template if condition

[castai-pod-node-lifecycle] Fix pod-disrubtion-budget if condition

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-configmap.yaml

https://castai.slack.com/archives/C049JU55L4F/p1676384691977439?thread_ts=1676299466.351299&cid=C049JU55L4F

[castai-agent] Agent base ram increase through cpvpa-configmap

---

charts/castai-spot-handler/Chart.yaml
charts/castai-spot-handler/ci/test-values.yaml
charts/castai-spot-handler/templates/daemonset.yaml

Add podAnnotations support to castai-spot-handler

[castai-spot-handler] add podAnnotations support to castai-spot-handler

---

charts/castai-cluster-controller/Chart.yaml

- Log CAST AI components deleted/evicted by controller

[castai-cluster-controller] Bump ctrl version v0.34.3

---

charts/castai-agent/Chart.yaml
charts/castai-agent/ci/secret-ref-values.yaml
charts/castai-agent/ci/test-values.yaml

Release notes: https://github.com/castai/k8s-agent/releases/tag/v0.43.0

[castai-agent] bump agent version to v0.43.0

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-deployment.yaml
charts/castai-agent/templates/deployment.yaml

Agent is now able to observe it's own health and send diagnostic info to mothership.

[castai-agent] add agent's self-monitor

---

.github/workflows/release.yaml
.github/workflows/validate-pr.yaml
charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-deployment.yaml
charts/castai-agent/templates/deployment.yaml
cnab-config/README.md
cnab-config/castai-agent/createUIDefinition.json
cnab-config/castai-agent/mainTemplate.json
cnab-config/castai-agent/manifest.yaml
cnab-config/castai-agent/values.yaml
scripts/handle-cnab-package.sh

- Update `Validate` and `Release` Github actions to support verifying and building CNAB bundle package for `castai-agent`.
- Update `castai-agent` Helm charts image spec and some labels required by Azure CNAB bundle. 
-  Add required Azure ARM template, UI definition and ARM Manifest to support CNAB bundle packaging for `castai-agent`.

[castai-agent] automate CNAB packaging

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-deployment.yaml
charts/castai-agent/values.yaml

Allow overriding cpvpa image with custom registry/repository

[castai-agent] move cpvpa image repository to values

---

.github/workflows/release-cnab.yaml
.github/workflows/release.yaml
.github/workflows/validate-pr.yaml
charts/castai-agent/Chart.yaml
scripts/release-cnab-package.sh
scripts/verify-cnab-package.sh

Moved CNAB package release to separate workflow `release-cnab` which will be triggered on tags creation.

[castai-agent] release CNAB package on tag creation

---

.github/workflows/lint-test.yaml
charts/castai-agent/Chart.yaml
cnab-config/castai-agent/createUIDefinition.json
cnab-config/castai-agent/mainTemplate.json

Change name to `castai-agent` to match internal naming

[castai-agent] Name change to castai-agent

---

.github/workflows/release.yaml
charts/castai-agent/Chart.yaml

[castai-agent] Move to PAT for release

---

charts/castai-cluster-controller/Chart.yaml

Update cluster controller version to include better delete/create/status checker for nodes

[castai-cluster-controller] Update cluster controller version

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/rbac.yaml

collect ConfigMaps with the snapshot

[castai-agent] collect ConfigMaps with the snapshot

---

charts/castai-cluster-controller/Chart.yaml

Add identity to cluster controller

[castai-cluster-controller] Controller logging (2)

---

charts/castai-cluster-controller/Chart.yaml

[castai-cluster-controller] Update helm chart

---

charts/castai-agent/Chart.yaml
charts/castai-agent/README.md
charts/castai-agent/templates/deployment.yaml
charts/castai-agent/values.yaml

add resource request default values
use resource values in template

[castai-agent] enable resources override

---

charts/castai-hibernate/Chart.yaml
charts/castai-hibernate/README.md
charts/castai-hibernate/templates/pause-cronjob.yaml
charts/castai-hibernate/templates/resume-cronjob.yaml
charts/castai-hibernate/values.yaml

Adding the timezone to the hibernate job

[castai-hibernate] adding timezone to hibernate

---

charts/castai-cluster-controller/Chart.yaml

Change list:
https://github.com/castai/cluster-controller/releases/tag/v0.39.3

[castai-cluster-controller] Update controller

---

charts/castai-hibernate/Chart.yaml

[castai-hibernate] Update appVersion to v0.7

[castai-hibernate] Update appVersion to v0.7

---

charts/castai-cluster-controller/Chart.yaml

See https://github.com/castai/cluster-controller/releases/tag/v0.41.8 for included changes

[castai-cluster-controller] Bump cluster controller version in chart

---

charts/castai-audit-logs-receiver/Chart.yaml
charts/castai-audit-logs-receiver/README.md
charts/castai-audit-logs-receiver/ci/test-values.yaml
charts/castai-audit-logs-receiver/templates/statefulset.yaml
charts/castai-audit-logs-receiver/values.yaml

Add imagePullSecret support for audit-log-reciever

[castai-audit-logs-receiver] Add imagePullSecrets into audit-logs-reciever

---

charts/castai-agent/Chart.yaml
charts/castai-agent/README.md
charts/castai-agent/templates/rbac.yaml
charts/castai-agent/values.yaml

These few resources are needed for security best practices and compliance features

[castai-agent] Read ingress and rbac resources

---

charts/castai-cloud-proxy/Chart.yaml
charts/castai-cloud-proxy/README.md
charts/castai-cloud-proxy/ci/test-values.yaml
charts/castai-cloud-proxy/templates/_helpers.tpl
charts/castai-cloud-proxy/templates/deployment.yaml
charts/castai-cloud-proxy/templates/pod-disruption-budget.yaml
charts/castai-cloud-proxy/templates/secret.yaml
charts/castai-cloud-proxy/values.yaml
charts/castai-cluster-controller/Chart.lock

Note: not complete but should deploy the service in the cluster. Working on adjusting settings and secrets.

[castai-cloud-proxy]  KUBE-503: Helm additions for cloud-proxy

---

charts/castai-cluster-controller/Chart.yaml

Reverts castai/helm-charts#537

[castai-cluster-controller] auto approve csr feature

---

charts/castai-spot-handler/Chart.yaml

See https://github.com/castai/spot-handler/releases/tag/v0.14.0

[castai-spot-handler] NOJIRA: (chore) Bump spot-handler with updated packages

---

charts/castai-cluster-controller/Chart.yaml

https://github.com/castai/cluster-controller/releases/tag/v0.54.6

[castai-cluster-controller] update cluster-controller to v0.54.6

---

.github/workflows/validate-pr.yaml

Disable CNAB validation for now

NOJIRA: disable cnab validation

---

.github/workflows/lint-test.yaml
charts/castai-agent/Chart.yaml

k8s-agent release: https://github.com/castai/k8s-agent/releases/tag/v0.77.0

[castai-agent] Update agent to v0.77.0

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/templates/clusterrole.yaml
charts/castai-evictor/templates/rbac.yaml

Reverts castai/helm-charts#667

[castai-evictor] Revert: Make evictor's lease namespaced

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/templates/envoy_config.yaml
charts/castai-db-optimizer/values.yaml

Adds an option to turn on network debug logging for the database protocol

[castai-db-optimizer] allow debug logs of network traffic

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/ci/test-aks-values.yaml
charts/castai-cluster-controller/ci/test-values.yaml
charts/castai-cluster-controller/templates/deployment.yaml

https://github.com/castai/cluster-controller/releases/tag/v0.55.0  - feat: max actions in progress

[castai-cluster-controller] update cluster-controller - limit maxActionInProgress

---

charts/castai-spot-handler/Chart.yaml

release: https://github.com/castai/spot-handler/releases/tag/v0.17.0

[castai-spot-handler] bump spot-handler version v0.17.0

---

charts/castai-agent/Chart.yaml

release https://github.com/castai/k8s-agent/releases/tag/v0.83.0

[castai-agent] bump agent version v0.83.0

---

charts/castai-audit-logs-receiver/Chart.yaml
charts/castai-audit-logs-receiver/README.md
charts/castai-audit-logs-receiver/values.yaml

* Default exporter changed from logging to debug

[castai-audit-logs-receiver] bump to latest version

---

charts/castai-cluster-controller/Chart.yaml

Release non-namespace object creation

[castai-cluster-controller] v0.80.1 (app v0.56.1)

---

charts/castai-pod-mutator/Chart.yaml
charts/castai-pod-mutator/README.md

[castai-pod-mutator] Bump app version to v0.0.15 and chart version to v0.0.25

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/README.md
charts/castai-cluster-controller/templates/deployment.yaml
charts/castai-cluster-controller/values.yaml

Adding support for security context at container level for cluster controller to set allowPrivilegeEscalation to  false

[castai-cluster-controller] add support for security-context

---

charts/castai-pod-pinner/Chart.yaml
charts/castai-pod-pinner/README.md

This one contains the latest Kubernetes.

[castai-pod-pinner] v1.3.0 (app v1.4.0)

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/child-charts/castai-evictor-ext/templates/clusterrole.yaml
charts/castai-evictor/templates/deployment.yaml
charts/castai-evictor/values.yaml

This commit adds support for WOOP recommendations to Evictor.
It will make Evictor take WOOP recommendations into account when it runs its eviction simulations.

[castai-evictor] feat(evictor): support WOOP recommendations

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/templates/deployment.yaml
charts/castai-evictor/values.yaml

changing  security context at container level for evictor deployment to set allowPrivilegeEscalation to false

[castai-evictor] change value for security context in evictor 

---

charts/castai-cluster-controller/Chart.yaml

https://github.com/castai/cluster-controller/releases/tag/v0.57.3

[castai-cluster-controller] KUBE-1098: fix vulnerabilities

---

charts/castai-spot-handler/Chart.yaml

https://github.com/castai/spot-handler/releases/tag/v0.17.1

[castai-spot-handler] KUBE-1098: fix vulnerabilities

---

.github/workflows/validate-pr.yaml

This will get looked at but for the time being. This validation is being disabled.

fix: disable CNAB Validation

---

charts/castai-agent/Chart.yaml

v0.90.0 release notes https://github.com/castai/k8s-agent/releases/tag/v0.90.0

[castai-agent] bump agent image version

---

charts/castai-spot-handler/Chart.yaml

https://github.com/castai/spot-handler/pull/30

[castai-spot-handler] CSU-3490: fix vulnerabilities

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/templates/clustervpa-configmap.yaml
charts/castai-evictor/values.yaml

This PR will allow overriding the default configuration of evictor's cpvpa via values.yaml.
If not provided, the default will be used.

[castai-evictor] feat: allow configuration override for evictor cpvpa

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md

Bump castai-db-optimizer to version 0.39.1

[castai-db-optimizer] POLY-745: Bump chart version to 0.39.1

---

charts/castai-agent/Chart.yaml
charts/castai-agent/templates/clustervpa-configmap.yaml
charts/castai-agent/values.yaml

This PR will allow users to override castai-agent clusterVPA configuration.

[castai-agent] allow castai-agent cpvpa configuration override

---

charts/castai-evictor/Chart.yaml
charts/castai-evictor/README.md
charts/castai-evictor/child-charts/castai-evictor-ext/Chart.yaml
charts/castai-evictor/child-charts/castai-evictor-ext/README.md
charts/castai-evictor/child-charts/castai-evictor-ext/templates/clusterrole.yaml
charts/castai-evictor/values.yaml

1. Update live migration rbac in evictor.

[castai-evictor] Update live migrations rbac.

---

charts/castai-cluster-controller/Chart.yaml
charts/castai-cluster-controller/templates/rbac.yaml

We'll be using cluster-constroller to create PodMutation custom resources.

[castai-cluster-controller] Add RBAC rule for creating PodMutation resources

---

charts/castai-db-optimizer/Chart.yaml
charts/castai-db-optimizer/README.md
charts/castai-db-optimizer/templates/_versions.tpl

Use length-encoded integers for column count in text resultset as specified in MySQL protocol

[castai-db-optimizer] column count fix for mysql protocol
